import { createPlayer } from './players'
import type { Player } from '../types/player'

/**
 * Seed roster from FIFA screenshots (2026-09-06):
 * 4 senior + 24 youth academy.
 */
export function createSeedPlayers(now = Date.now()): Player[] {
  const seniors: Player[] = [
    createPlayer({
      name: 'Matěj Liška',
      country: 'Slovakia',
      naturalPosition: 'GK',
      currentPosition: 'GK',
      secondaryPositions: '',
      ovr: 54,
      height: "6'2\"",
      potRange: '',
      status: null,
      source: 'Academy',
      initialSM: 1,
      currentSM: 1,
      initialWF: 5,
      currentWF: 5,
      initialWorkRate: 'L/L',
      currentWorkRate: 'L/L',
      squadLocation: 'senior',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Breno Duarte',
      country: 'Brazil',
      naturalPosition: 'RB',
      currentPosition: 'RB',
      secondaryPositions: 'LB',
      ovr: 58,
      height: "5'5\"",
      potRange: '',
      status: null,
      source: 'Academy',
      initialSM: 4,
      currentSM: 4,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'L/H',
      currentWorkRate: 'L/H',
      squadLocation: 'senior',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Pedro Conceição',
      country: 'Brazil',
      naturalPosition: 'CDM',
      currentPosition: 'CDM',
      secondaryPositions: 'CB',
      ovr: 57,
      height: "5'11\"",
      potRange: '83-89',
      status: null,
      source: 'Academy',
      initialSM: 4,
      currentSM: 4,
      initialWF: 5,
      currentWF: 5,
      initialWorkRate: 'L/L',
      currentWorkRate: 'L/L',
      squadLocation: 'senior',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Peetu Jaatinen',
      country: 'Finland',
      naturalPosition: 'CB',
      currentPosition: 'CB',
      secondaryPositions: '',
      ovr: 60,
      height: "6'0\"",
      potRange: '',
      status: null,
      source: 'Academy',
      initialSM: 2,
      currentSM: 2,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/H',
      currentWorkRate: 'M/H',
      squadLocation: 'senior',
      updatedAt: now,
    }),
  ]

  const academy: Player[] = [
    createPlayer({
      name: 'Jack Rogerson',
      country: 'Canada',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CDM',
      ovr: 51,
      height: "5'8\"",
      potRange: '88-94',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'L/H',
      currentWorkRate: 'L/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Evan Lee',
      country: 'Canada',
      naturalPosition: 'ST',
      currentPosition: 'ST',
      secondaryPositions: 'CF',
      ovr: 56,
      height: "6'0\"",
      potRange: '79-85',
      status: null,
      source: 'Academy',
      initialSM: 5,
      currentSM: 5,
      initialWF: 2,
      currentWF: 2,
      initialWorkRate: 'H/L',
      currentWorkRate: 'H/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Marcus Perry',
      country: 'Canada',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CAM',
      ovr: 54,
      height: "5'6\"",
      potRange: '82-88',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/L',
      currentWorkRate: 'M/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Leonardo Cardoso',
      country: 'Brazil',
      naturalPosition: 'RB',
      currentPosition: 'RB',
      secondaryPositions: 'LB',
      ovr: 58,
      height: "5'10\"",
      potRange: '78-94',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 5,
      currentWF: 5,
      initialWorkRate: 'L/H',
      currentWorkRate: 'L/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Dani Rivas',
      country: 'Argentina',
      naturalPosition: 'CDM',
      currentPosition: 'CDM',
      secondaryPositions: 'CM',
      ovr: 49,
      height: "6'3\"",
      potRange: '81-87',
      status: null,
      source: 'Academy',
      initialSM: 4,
      currentSM: 4,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/M',
      currentWorkRate: 'M/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Renato Alves',
      country: 'Brazil',
      naturalPosition: 'CDM',
      currentPosition: 'CDM',
      secondaryPositions: '',
      ovr: 59,
      height: "6'3\"",
      potRange: '81-91',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'L/H',
      currentWorkRate: 'L/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Eduardo Cruz',
      country: 'Brazil',
      naturalPosition: 'CF',
      currentPosition: 'CF',
      secondaryPositions: 'ST, CAM',
      ovr: 64,
      height: "5'9\"",
      potRange: '79-94',
      status: null,
      source: 'Academy',
      initialSM: 5,
      currentSM: 5,
      initialWF: 2,
      currentWF: 2,
      initialWorkRate: 'L/L',
      currentWorkRate: 'L/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Alberto Hidalgo',
      country: 'Argentina',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CAM',
      ovr: 60,
      height: "5'7\"",
      potRange: '84-94',
      status: null,
      source: 'Academy',
      initialSM: 4,
      currentSM: 4,
      initialWF: 2,
      currentWF: 2,
      initialWorkRate: 'H/M',
      currentWorkRate: 'H/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Iván Albornoz',
      country: 'Argentina',
      naturalPosition: 'LM',
      currentPosition: 'LM',
      secondaryPositions: 'CAM',
      ovr: 52,
      height: "5'8\"",
      potRange: '79-85',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 4,
      currentWF: 4,
      initialWorkRate: 'M/H',
      currentWorkRate: 'M/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Fabricio Montero',
      country: 'Argentina',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CAM',
      ovr: 55,
      height: "5'11\"",
      potRange: '82-88',
      status: null,
      source: 'Academy',
      initialSM: 2,
      currentSM: 2,
      initialWF: 5,
      currentWF: 5,
      initialWorkRate: 'M/M',
      currentWorkRate: 'M/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Caio Azevedo',
      country: 'Brazil',
      naturalPosition: 'LB',
      currentPosition: 'LB',
      secondaryPositions: '',
      ovr: 59,
      height: "5'7\"",
      potRange: '81-87',
      status: null,
      source: 'Academy',
      initialSM: 2,
      currentSM: 2,
      initialWF: 5,
      currentWF: 5,
      initialWorkRate: 'L/H',
      currentWorkRate: 'L/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Patrick MacDonald',
      country: 'Canada',
      naturalPosition: 'CF',
      currentPosition: 'CF',
      secondaryPositions: 'ST',
      ovr: 58,
      height: "5'10\"",
      potRange: '84-90',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'H/M',
      currentWorkRate: 'H/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Borja Figueroa',
      country: 'Argentina',
      naturalPosition: 'RW',
      currentPosition: 'RW',
      secondaryPositions: 'RM, LW, CAM',
      ovr: 55,
      height: "5'6\"",
      potRange: '79-87',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 2,
      currentWF: 2,
      initialWorkRate: 'M/L',
      currentWorkRate: 'M/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Miguel Correia',
      country: 'Brazil',
      naturalPosition: 'LWB',
      currentPosition: 'LWB',
      secondaryPositions: '',
      ovr: 60,
      height: "5'10\"",
      potRange: '78-84',
      status: null,
      source: 'Academy',
      initialSM: 2,
      currentSM: 2,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'H/M',
      currentWorkRate: 'H/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Felipe de Oliveira',
      country: 'Brazil',
      naturalPosition: 'CF',
      currentPosition: 'CF',
      secondaryPositions: '',
      ovr: 56,
      height: "6'0\"",
      potRange: '82-92',
      status: null,
      source: 'Academy',
      initialSM: 4,
      currentSM: 4,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'H/H',
      currentWorkRate: 'H/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Julen Pérez',
      country: 'Argentina',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CAM',
      ovr: 48,
      height: "5'10\"",
      potRange: '79-89',
      status: null,
      source: 'Academy',
      initialSM: 4,
      currentSM: 5,
      initialWF: 5,
      currentWF: 5,
      initialWorkRate: 'M/M',
      currentWorkRate: 'M/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Rafael Pinto',
      country: 'Brazil',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CDM',
      ovr: 48,
      height: "5'7\"",
      potRange: '74-94',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 1,
      currentWF: 1,
      initialWorkRate: 'H/H',
      currentWorkRate: 'H/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Pedro Martins',
      country: 'Brazil',
      naturalPosition: 'RWB',
      currentPosition: 'RWB',
      secondaryPositions: '',
      ovr: 65,
      height: "5'9\"",
      potRange: '71-91',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/M',
      currentWorkRate: 'M/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Carlos Rodrigues',
      country: 'Brazil',
      naturalPosition: 'LB',
      currentPosition: 'LB',
      secondaryPositions: '',
      ovr: 56,
      height: "5'9\"",
      potRange: '78-94',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/M',
      currentWorkRate: 'M/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Cristian Escobar',
      country: 'Argentina',
      naturalPosition: 'CAM',
      currentPosition: 'CAM',
      secondaryPositions: 'CM',
      ovr: 47,
      height: "5'6\"",
      potRange: '69-93',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 4,
      currentWF: 4,
      initialWorkRate: 'H/L',
      currentWorkRate: 'H/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Lucas Corona',
      country: 'Argentina',
      naturalPosition: 'ST',
      currentPosition: 'ST',
      secondaryPositions: '',
      ovr: 45,
      height: "5'7\"",
      potRange: '74-90',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/L',
      currentWorkRate: 'M/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Joaquín Serrano',
      country: 'Argentina',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CAM',
      ovr: 41,
      height: "5'7\"",
      potRange: '73-93',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/M',
      currentWorkRate: 'M/M',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Alfonso Martins',
      country: 'Portugal',
      naturalPosition: 'CM',
      currentPosition: 'CM',
      secondaryPositions: 'CDM, CAM',
      ovr: 46,
      height: "5'10\"",
      potRange: '71-91',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/L',
      currentWorkRate: 'M/L',
      squadLocation: 'academy',
      updatedAt: now,
    }),
    createPlayer({
      name: 'Fabião Izquierdo',
      country: 'Portugal',
      naturalPosition: 'RB',
      currentPosition: 'RB',
      secondaryPositions: 'LB',
      ovr: 65,
      height: "5'9\"",
      potRange: '71-94',
      status: null,
      source: 'Academy',
      initialSM: 3,
      currentSM: 3,
      initialWF: 3,
      currentWF: 3,
      initialWorkRate: 'M/H',
      currentWorkRate: 'M/H',
      squadLocation: 'academy',
      updatedAt: now,
    }),
  ]

  return [...seniors, ...academy]
}
